dist: xenial
language: python
python:
- '3.6'
env:
  global:
  - secure: oxZkEIKP290fDZECZLi4vLX1W3IVZ1GNh5IOUkjfIbp1DafYfFjSSLUUICL1SWkv7AyasjKvZa4ZhdTn2jdbFIIGyZ4VYb2R0h7AVNy4e/kIJCvRAbYCNCZMIgBbUFFc8s8Lrn5i5aZ+9ZQmn1p8gQQ8V38Nivz5OEONVWb58Vgcg3ZXs+XHeo5nEFNOZcCGcGFe4PzaxbHILZ2bxe6HbMWDs/3cf9n2PgGxDvOz0v9xQZjYfC9fqe2sRYrceo6yf53JttHz/83tO7ey40/Ajq281414kghVCTioEhG4utQ3Vvy3M7d4rI0+WubBAzUe/AiLzZBngRs5lsMo43iVnc95ncf4LyTg3gcZLcA4kBCDXEaEUVH0xbrgPkUUl25QeIe7hVJLrrO9DMJ6hLvg+MJBaA/257mEBsES95V9ck8UZqNBKqf0xgmPWbezC3qD0q/FOUgazSJqtab0FnvGpPEJ+YJv4rfVbDs8c8ZudAJAUrQxvUTu8O3CabCSrpxAuCCI+0Sx4/OMxBv5YrDzCPs4spFeK+UVKY+4zN3wTshYY1lOBNK1GTFfoOWpSRhVEwoP9mPsHmHdupsOeyZiCrfCcF3MZncl6XZA0W8elUcIpVbK9oKWnimFYEl3+44qHDEnjqB56WQjv3mJ62kcUHKGuGJlfhkzcRjxGG1FGv8=
  - secure: T2DhGDi3QgUI2dRUscYYdKw9qEAeWnKwkDE3ZhwYiU/s8w3EkcCx7zulyNaOeENxywCUMvTRPn4OKgWJPZ1rELXY3s8kTdsP+l0zMtFuqG+KnvVwFgIrQkLXsJaMQ3cNguHSk3lFvnNJ/CVDF6xbQ6LYSYKNYPlgjYIv80VZdRQbFkzejljY/bqM/vL7o6ea0lnwLAnbcQEy8jLHIsi5K72LxauVmZGeDGu7wC09vCB13mX/LhJP9hDQLnolBG07oJshhqa/DZkLwB/7uIM1LfABcWAAoPjoc9sKjVOqoqDsULXhBLpsfHDrMMORtFTbJcMB8L0c2vtLiYqvjbe+cT1QRJep44avETBqcKKGtL7CRLxQrQKV9I/x9CEO3R24qhQH+ih59PwahRDYiC1IhGgwXFrlmohPpCcAbum2Qitv0MdqPeqslssxdfqvq5FwJb7YBKwVdErBfQVm0QtuF0LfIiik4i89gaYRXgBEsaAJFGOLgTg98NzVD+clO8Gj0gSKWAmatdIPQ/Ic50wluh3rpolAQI/8aU2untMqhRoQYBPTArawfCch4zhSbs89bBDvr2IQ/qKDVZmtXSp7fIzVXXifTL5n0PfA0xMRBv9VPie09GRnrgACXUKN2f9DGEq1QRB0P6Iz0NPfTRiPfVPHQxMXDpm993NxL8ttRfI=
install:
- pip install -r requirements.txt
- export PYTHONPATH=`pwd`
- echo $API_KEY >> ./wa_config.txt
- echo $WORKSPACE_ID >> ./wa_config.txt
script:
- python -m unittest discover
