dist: xenial
language: python
python:
- '3.6'

install:
- openssl aes-256-cbc -K $encrypted_56e07cd7ba73_key -iv $encrypted_56e07cd7ba73_iv -in wa_config.txt.enc -out wa_config.txt -d
- pip install -r requirements.txt
- export PYTHONPATH=`pwd`

script:
- python -m unittest discover
